/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A launched browser. Cheap wrapper over a shared [`Engine`]. */
export declare class Browser {
  /** puppeteer `browser.newPage()` — a page in a fresh isolated context. */
  newPage(): Page
  /**
   * puppeteer `browser.createBrowserContext()` — an isolated context. Each
   * page created under it already gets its own engine-level browser context,
   * so isolation is preserved.
   */
  createBrowserContext(): BrowserContext
  /** puppeteer `browser.close()` — shut Chromium down. */
  close(): Promise<void>
}

/** An isolated browsing context (puppeteer `BrowserContext`). */
export declare class BrowserContext {
  /** puppeteer `context.newPage()`. */
  newPage(): Page
  /**
   * puppeteer `context.close()`. Pages under this context each own their
   * engine session and are closed via `page.close()`; this is a no-op kept
   * for API compatibility.
   */
  close(): Promise<void>
}

/** A page = one persistent [`BrowserSession`] in its own Chromium context. */
export declare class Page {
  /** puppeteer `page.setContent(html, options)`. */
  setContent(html: string, options?: SetContentOptions | undefined | null): Promise<void>
  /**
   * puppeteer `page.evaluate(fn)`. Receives a JS expression string (the JS
   * facade stringifies a passed function) and returns the result as a JSON
   * string, awaiting any returned promise (`() => document.fonts.ready`).
   */
  evaluate(script: string): Promise<string>
  /**
   * puppeteer `page.goto(url, options)`. Honors `waitUntil` (load /
   * domcontentloaded resolve on the navigation; networkidle0/2 add a settle).
   * NOTE: a custom `timeout` is not yet plumbed through — the engine's default
   * navigation timeout applies.
   */
  goto(url: string, options?: GotoOptions | undefined | null): Promise<void>
  /** puppeteer `page.pdf(options)` — returns a Node Buffer of PDF bytes. */
  pdf(options?: NodePdfOptions | undefined | null): Promise<Buffer>
  /** puppeteer `page.close()`. */
  close(): Promise<void>
}

/** puppeteer `page.goto(url, options)`. */
export interface GotoOptions {
  waitUntil?: string
  timeout?: number
}

/** puppeteer `puppeteer.launch(options)`. */
export declare function launch(options?: LaunchOptions | undefined | null): Promise<Browser>

/** puppeteer `launch(options)`. */
export interface LaunchOptions {
  /**
   * Headless mode. kitewright always runs headless; a `false` here is
   * accepted but ignored (documented in the compatibility matrix).
   */
  headless?: boolean
  /** Chromium args. `--no-sandbox` is honored; other args are ignored. */
  args?: Array<string>
  /**
   * Path to a Chrome/Chromium/chrome-headless-shell binary. Falls back to the
   * `BROWSER_EXECUTABLE` env var, then to auto-detection.
   */
  executablePath?: string
}

/** puppeteer `page.pdf(options)`. */
export interface NodePdfOptions {
  /** "a4" (default) | "letter" | "legal" | "a3". */
  format?: string
  landscape?: boolean
  printBackground?: boolean
  displayHeaderFooter?: boolean
  headerTemplate?: string
  footerTemplate?: string
  margin?: PdfMargin
  scale?: number
  preferCssPageSize?: boolean
}

/** puppeteer margin object (CSS lengths like "20px", "1cm"). */
export interface PdfMargin {
  top?: string
  bottom?: string
  left?: string
  right?: string
}

/** puppeteer `page.setContent(html, options)`. */
export interface SetContentOptions {
  /** "load" (default) | "domcontentloaded" | "networkidle0". */
  waitUntil?: string
  /** Accepted for API-compatibility; the engine time-boxes internally. */
  timeout?: number
}
